import React from 'react'
import { useTranslation } from 'react-i18next'
import { useAuth } from '../hooks/useAuth'
import OnboardingForm from '../components/auth/OnboardingForm'
import { BookOpen } from 'lucide-react'

function OnboardingPage() {
  const { t } = useTranslation()
  const { user } = useAuth()

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-blue-100 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex items-center justify-center gap-2 mb-6">
            <BookOpen className="w-12 h-12 text-primary-600" />
            <span className="text-4xl font-bold text-gray-900">StudyGenie</span>
          </div>
          
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            {t('onboarding.welcome', 'Welcome to StudyGenie, {{name}}!', { name: user?.name?.split(' ')[0] || 'Student' })}
          </h1>
          
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            {t('onboarding.subtitle', 'Let\'s personalize your learning experience with a few quick questions')}
          </p>
        </div>

        {/* Onboarding Form */}
        <div className="bg-white rounded-lg shadow-lg p-8">
          <OnboardingForm />
        </div>

        {/* Features Preview */}
        <div className="mt-12 grid md:grid-cols-3 gap-6 text-center">
          <div className="bg-white/50 backdrop-blur-sm rounded-lg p-6">
            <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mx-auto mb-4">
              <span className="text-2xl">🤖</span>
            </div>
            <h3 className="font-semibold text-gray-900 mb-2">
              {t('onboarding.preview.ai', 'AI-Powered Learning')}
            </h3>
            <p className="text-sm text-gray-600">
              {t('onboarding.preview.aiDesc', 'Get personalized study materials generated by advanced AI')}
            </p>
          </div>

          <div className="bg-white/50 backdrop-blur-sm rounded-lg p-6">
            <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mx-auto mb-4">
              <span className="text-2xl">🌍</span>
            </div>
            <h3 className="font-semibold text-gray-900 mb-2">
              {t('onboarding.preview.multilingual', 'Multilingual Support')}
            </h3>
            <p className="text-sm text-gray-600">
              {t('onboarding.preview.multilingualDesc', 'Study in your preferred language with 70+ options')}
            </p>
          </div>

          <div className="bg-white/50 backdrop-blur-sm rounded-lg p-6">
            <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mx-auto mb-4">
              <span className="text-2xl">📈</span>
            </div>
            <h3 className="font-semibold text-gray-900 mb-2">
              {t('onboarding.preview.progress', 'Progress Tracking')}
            </h3>
            <p className="text-sm text-gray-600">
              {t('onboarding.preview.progressDesc', 'Monitor your learning journey with detailed analytics')}
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default OnboardingPage
